#ifndef GLOBALS_H
#define GLOBALS_H

#define MAX_ID_SIZE 30
#define MAX_FULL_NAME_SIZE 1000
#define MAX_AGE_CHARS_SIZE 2

#define SPACE 1

#define MAX_DATA_SIZE \
    (MAX_ID_SIZE + SPACE + MAX_FULL_NAME_SIZE + SPACE + MAX_AGE_CHARS_SIZE)

#define MAX_INPUT_SIZE (SPACE + SPACE + MAX_DATA_SIZE)

#endif